# Generated by Django 3.1.7 on 2021-04-21 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=50, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('Category_Desc', models.CharField(max_length=150, null=True)),
                ('vendname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vend')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subcategory_Name', models.CharField(max_length=50, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('Subcategory_Desc', models.CharField(max_length=150, null=True)),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('vendname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vend')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, null=True)),
                ('Image1', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('Product_Desc', models.CharField(max_length=150, null=True)),
                ('Price', models.FloatField(null=True)),
                ('Stock', models.IntegerField(null=True)),
                ('Stock_status', models.CharField(max_length=30, null=True)),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('Subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.subcategory')),
                ('vendname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vend')),
            ],
        ),
    ]
